<?php

declare(strict_types=1);

namespace ProSql\Schema;

/**
 * Writes one timestamped .sql file per `apc build` run covering every
 * entity that had anything to say — the "before that create one
 * migration script" half of the feature: a plain-text record of exactly
 * what was (or wasn't) applied, so a "complex" change never just
 * vanishes silently, even under TABLE_WRITE=fixed where nothing at all
 * gets touched.
 *
 * Best-effort, the same way Runner::writeCache() is for the route
 * cache: a missing/unwritable storage/migrations directory just means
 * no file gets written, not a failed build.
 */
final class MigrationWriter
{
    public function __construct(private readonly string $migrationsPath)
    {
    }

    /**
     * @param list<array{
     *     table: string,
     *     applied: list<string>,
     *     deferred: list<array{sql: string, reason: string}>,
     * }> $entries
     * @return string|null the written file's path, or null if there was nothing to write (or it couldn't be)
     */
    public function write(array $entries): ?string
    {
        $entries = array_values(array_filter(
            $entries,
            static fn (array $entry): bool => $entry['applied'] !== [] || $entry['deferred'] !== [],
        ));

        if ($entries === []) {
            return null;
        }

        if (!is_dir($this->migrationsPath) && !mkdir($this->migrationsPath, 0775, true) && !is_dir($this->migrationsPath)) {
            return null;
        }

        if (!is_writable($this->migrationsPath)) {
            return null;
        }

        $tables = array_column($entries, 'table');
        $path = $this->migrationsPath . '/' . date('Y_m_d_His') . '_' . implode('_', $tables) . '.sql';

        $lines = ['-- Generated by `apc build` on ' . date(DATE_ATOM), ''];

        foreach ($entries as $entry) {
            $lines[] = "-- Table: {$entry['table']}";

            foreach ($entry['applied'] as $sql) {
                $lines[] = '-- SAFE (already applied):';
                $lines[] = $sql;
                $lines[] = '';
            }

            foreach ($entry['deferred'] as $item) {
                $lines[] = "-- COMPLEX (NOT applied — {$item['reason']}):";
                $lines[] = '-- ' . $item['sql'];
                $lines[] = '';
            }
        }

        file_put_contents($path, implode("\n", $lines) . "\n");

        return $path;
    }
}
