-- Generated by `apc build` on 2026-08-24T14:59:29+00:00

-- Table: posts
-- SAFE (already applied):
CREATE TABLE `posts` (
  `id` CHAR(36) NOT NULL DEFAULT (lower(concat(hex(random_bytes(4)), '-', hex(random_bytes(2)), '-4', substr(hex(random_bytes(2)), 2, 3), '-', hex(floor(ascii(random_bytes(1)) / 64) + 8), substr(hex(random_bytes(2)), 2, 3), '-', hex(random_bytes(6))))),
  `userId` CHAR(36) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_posts_userId` FOREIGN KEY (`userId`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

