-- Generated by `gg build` on 2026-09-02T08:32:05+00:00

-- Table: posts
-- SAFE (already applied):
CREATE TABLE `posts` (
  `id` CHAR(36) NOT NULL DEFAULT (lower(concat(hex(random_bytes(4)), '-', hex(random_bytes(2)), '-4', substr(hex(random_bytes(2)), 2, 3), '-', hex(floor(ascii(random_bytes(1)) / 64) + 8), substr(hex(random_bytes(2)), 2, 3), '-', hex(random_bytes(6))))),
  `userId` CHAR(36) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- COMPLEX (NOT applied — referenced table `users` doesn't exist yet):
-- ALTER TABLE `posts` ADD CONSTRAINT `fk_posts_userId` FOREIGN KEY (`userId`) REFERENCES `users` (`id`);

-- Table: users
-- SAFE (already applied):
CREATE TABLE `users` (
  `id` CHAR(36) NOT NULL DEFAULT (lower(concat(hex(random_bytes(4)), '-', hex(random_bytes(2)), '-4', substr(hex(random_bytes(2)), 2, 3), '-', hex(floor(ascii(random_bytes(1)) / 64) + 8), substr(hex(random_bytes(2)), 2, 3), '-', hex(random_bytes(6))))),
  `name` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

