-- Generated by `apc build` on 2026-08-24T13:59:33+00:00

-- Table: users
-- COMPLEX (NOT applied — a column type/nullability change — needs TABLE_WRITE=force, review first):
-- ALTER TABLE `users` MODIFY COLUMN `id` CHAR(36) NOT NULL;

