<?php

declare(strict_types=1);

namespace App;

use App\Services\PostService;
use App\Services\UserService;
use Gerogo\Attributes\BaseRoot;
use Gerogo\Attributes\PageController;
use Gerogo\Attributes\RestController;
use Gerogo\ClassDiscovery;
use Gerogo\Container;
use Gerogo\Module;
use Gerogo\Runner;
use ProSql\Attributes\ProEntity;

/**
 * The application's main class — equivalent to a @SpringBootApplication
 * class: it declares which services get bound into the container and which
 * controllers get wired into the router when the app boots. The
 * controller list itself lives in runner/controllers.php, read here via
 * Runner::get('controllers') rather than hardcoded.
 */
#[BaseRoot('/ap/v1')]
class Application extends Module
{
    public function register(Container $container): void
    {
        $container->singleton(UserService::class);
        $container->singleton(PostService::class);
    }

    public function controllers(): array
    {
        return Runner::get('controllers');
    }

    /**
     * `apc build --clean` regenerates runner/controllers.php and
     * runner/entities.php from what's actually in the filesystem right
     * now, via Gerogo\ClassDiscovery — every #[RestController] or
     * #[PageController] class under src/Controllers/ or lib/controllers/,
     * and every #[ProEntity] class under src/Entities/ — rather than
     * trusting a hand-maintained list that can silently drift out of
     * sync, or simply disappear if the file itself is ever lost. Which
     * directories/attributes to scan is this method's call, not
     * ClassDiscovery's — it's an app-specific convention (this app
     * happens to split controllers across two directories, and across
     * the two controller attributes), not a framework one. Both
     * attributes are scanned across BOTH directories rather than
     * assuming "src/Controllers is REST-only, lib/controllers is
     * Page-only" — RouteCompiler is what actually enforces which
     * attribute a controller may carry, not where the file lives.
     *
     * @return array<string, string>
     */
    public function runnerTemplate(): array
    {
        $basePath = Runner::get('base_path');
        $controllerDirectories = ["$basePath/src/Controllers", "$basePath/lib/controllers"];

        $controllerClasses = array_values(array_unique([
            ...ClassDiscovery::findClassesWithAttribute($basePath, $controllerDirectories, RestController::class),
            ...ClassDiscovery::findClassesWithAttribute($basePath, $controllerDirectories, PageController::class),
        ]));
        sort($controllerClasses);

        $entityClasses = ClassDiscovery::findClassesWithAttribute(
            $basePath,
            ["$basePath/src/Entities"],
            ProEntity::class,
        );

        return [
            'controllers.php' => self::classListTemplate(
                "The app's own controller classes — regenerated by `apc build --clean` "
                    . 'from every class under src/Controllers/ and lib/controllers/ that carries '
                    . '#[RestController] or #[PageController] (see Gerogo\ClassDiscovery). Consumed by '
                    . "App\\Application::controllers() via Runner::get('controllers'). A package "
                    . 'module (ProSqlModule, SessionModule, ...) still declares its own '
                    . "controllers() directly, since it isn't part of this app's manifest and "
                    . "isn't scanned here.",
                $controllerClasses,
            ),
            'entities.php' => self::classListTemplate(
                'Every #[ProEntity]-carrying class `apc build` should sync a table for — '
                    . 'regenerated by `apc build --clean` from every class under src/Entities/ '
                    . 'that carries #[ProEntity] (see Gerogo\ClassDiscovery). Consumed by '
                    . "ProSql\\ProSqlModule::build() via Runner::get('entities').",
                $entityClasses,
            ),
        ];
    }

    /** @param list<class-string> $classes */
    private static function classListTemplate(string $comment, array $classes): string
    {
        $commentLines = implode(
            "\n",
            array_map(static fn (string $line): string => "// $line", explode("\n", wordwrap($comment, 75, "\n", true))),
        );

        $entries = implode("\n", array_map(static fn (string $c): string => "    $c::class,", $classes));

        return <<<PHP
            <?php

            declare(strict_types=1);

            $commentLines

            return [
            $entries
            ];

            PHP;
    }
}
