<?php

declare(strict_types=1);

// The app's own controller classes — regenerated by `apc build --clean`
// from every class under src/Controllers/ and lib/controllers/ that carries
// #[RestController] or #[PageController] (see Gerogo\ClassDiscovery).
// Consumed by App\Application::controllers() via Runner::get('controllers').
// A package module (ProSqlModule, SessionModule, ...) still declares its own
// controllers() directly, since it isn't part of this app's manifest and
// isn't scanned here.

return [
    App\Controllers\AuthController::class,
    App\Controllers\HealthController::class,
    App\Controllers\HomeController::class,
    App\Controllers\PostController::class,
    App\Controllers\UserController::class,
    Lib\Controllers\AboutController::class,
    Lib\Controllers\ContactController::class,
    Lib\Controllers\DocsController::class,
    Lib\Controllers\HomeController::class,
    Lib\Controllers\ReleasesController::class,
];
