<?php

declare(strict_types=1);

// Every #[ProEntity]-carrying class `gg build` should sync a table for —
// regenerated by `gg build --clean` from every class under src/Entities/ that
// carries #[ProEntity] (see Gerogo\ClassDiscovery). Consumed by
// ProSql\ProSqlModule::build() via Runner::get('entities').

return [
    App\Entities\PostEntity::class,
    App\Entities\ProductEntity::class,
    App\Entities\UserEntity::class,
];
