<?php

declare(strict_types=1);

// Every #[ProEntity]-carrying class `apc build` should sync a table for —
// regenerated by `apc build --clean` from every class under src/Entities/
// that carries #[ProEntity] (see ApiPro\ClassDiscovery). Consumed by
// ProSql\ProSqlModule::build() via Runner::get('entities').

return [
    App\Entities\PostEntity::class,
    App\Entities\UserEntity::class,
];
